# Configuración de Nixpacks para un despliegue full-stack

[phases.install]
# Instala dependencias en la raíz (frontend) y en la carpeta del backend
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
# Construye la aplicación de React
cmds = ["npm run build"]

[start]
# Comando para iniciar el servidor de Node.js
# Este será el proceso principal del contenedor
cmd = "cd backend && npm start"
