# nixpacks.toml

# Define la imagen base para la ejecución. Al especificarla, evitamos que Nixpacks
# trate la aplicación como estática y añada Caddy.
runImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1741046653"

# Define las fases del proceso de construcción y despliegue.
[phases]

# Fase de configuración: instala las herramientas necesarias en el entorno de construcción.
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

# Fase de instalación: instala las dependencias tanto del frontend como del backend.
[phases.install]
cmds = ["npm install && cd backend && npm install"]

# Fase de construcción: ejecuta el script para compilar el frontend de React.
[phases.build]
cmds = ["npm run build"]

# Define el comando de inicio de la aplicación.
[start]
# Le dice a Coolify que el comando para arrancar el servidor está en la carpeta del backend.
cmd = "cd backend && npm start"
